findByUserId API method
CESNET/perun-proxy-api pull request #21
Opened 2020-08-20 13:29 UTC by pavolpluta

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code or performance improvement
- [ ] Documentation changes or improvements

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My code has tests
- [ ] My code has been tested manually
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2020-08-21 08:08 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserMiddleware.java
> +    User findByPerunUserId(DataAdapter preferredAdapter, int userId);
Add a blank line after the method declaration

2020-08-21 08:08 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
> +    User getUserById(int userId);
Stay consistent in method naming. In most of the cases, you have used **find** instead of the **get**. Stick to the one word (_find_ is prefered in this case). Also, add a blank line after the method declaration.

2020-08-21 08:09 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
> +
Remove one blank line

2020-08-21 08:10 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +    }
Add a blank line after the method body enclosing bracket.

2020-08-21 08:11 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +     * EXAMPLE CURL: TODO
If you need a cURL request in the documentation, this should be the correct one.

curl --request GET --url 'http://127.0.0.1:8081/proxyapi/auth/proxy-user/findByPerunUserId?userId=62692' --header 'authorization: Basic auth'

2020-08-24 11:41 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +        params.put(PARAM_MEMBER, userId);
I have no idea why I put PARAM_MEMBER there... Some copy-paste error

2020-08-24 11:44 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +     * EXAMPLE CURL: TODO
Thanks

2020-08-26 07:35 UTC, dBucik requested changes

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
> +    User findByPerunUserId(long userId);
Please change the type to "Long"

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserMiddleware.java
> +    User findByPerunUserId(DataAdapter preferredAdapter, long userId);
Change the type of userId to Long

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
> +    User findPerunUserById(long userId);
Change the type of userId to Long

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +        if (!this.connectorRpc.isEnabled()) {
Please check the current master branch. We have removed all such checks as the connector does the check instead.

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/configuration/MethodNameConstants.java
> +    public static final String FIND_BY_PERUN_USER_ID = "find_by_perun_user_id";
This whole file has been deleted on the master. Please rebase the pull request and put the constant into the appropriate class.

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +    public User findPerunUserById(long userId) {
We have switched to the Spring LDAP library. Check the current master for implementation of how to work with it.
Rebase the pull request on the current master branch and rewrite the method to use the SpringLDAP interface.

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +
We have switched to the Spring LDAP library. Check the current master for implementation of how to work with it.
Rebase the pull request on the current master branch and rewrite the method to use the SpringLDAP interface.

2020-08-26 07:35 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +import static cz.muni.ics.perunproxyapi.presentation.rest.controllers.ParameterConstants.PARAM_USER_ID;
This whole file has been deleted on the master. Please rebase the pull request and put the constant into the appropriate class.

2020-08-26 09:22 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +
Done. I've also made changes in getPerunUser() method to call this method concurrently with findPerunUserById() to prevent duplicates

2020-08-26 13:08 UTC, dBucik approved these changes

2020-08-27 06:56 UTC, vyskocilpavel approved these changes

2020-08-27 07:19 UTC, merged