Login api rework
CESNET/perun-proxy-api pull request #37
Opened 2020-09-02 11:25 UTC by pavolpluta

## Description
Changed login API method, updated User and UserDTO objects. New RPC Adapter method getUsersAttributeValue(). 
LDAP method missing so far.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Code or performance improvement
- [X] Documentation changes or improvements

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My code has tests
- [X] My code has been tested manually
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2020-09-03 10:52 UTC, dBucik requested changes
Also please rebase your code as new commits have been merged into master

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
> +            String attr = subNode.asText();
before converting to string, please check if the subNode is not equal to null (in object reference meaning)

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
> +
remove this blank line

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
> +                    userMiddleware.getAttributesValues(adapter, Entity.USER , user.getPerunId() , fieldsToUse);
Remove whitespaces before commas

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
>              userDTO = new UserDTO(
return this object directly

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
>          return userDTO;
return null directly

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +    public List<User> getUsersByAttributeValue(@NonNull String attributeName, @NonNull String attributeValue)
We will need to discuss some changes in place.

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/InvalidNumberOfValuesException.java
> +    }
add a blank line after the method enclosing bracket

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +     *   --url http://localhost:8081/papi/auth/proxy-user/3e65bd2aa4c818bd3579023939b546b69e1b75ee@einfra.cesnet.cz \
remove the actual login, replace it with some non-existing thing
use "proxyapi" instead of "papi"

2020-09-03 10:52 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +     * curl --request GET --url 'http://127.0.0.1:8081/papi/auth/proxy-user/findByPerunUserId?userId=62692'
revert this change, we want to use some more general path. Also please replace userId with 12345

2020-09-08 11:20 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +    public List<User> getUsersByAttributeValue(@NonNull String attributeName, @NonNull String attributeValue)
Functionality moved from facade to rpc adapter, check if it is all right, please.

2020-09-09 07:06 UTC, vyskocilpavel approved these changes

2020-09-09 07:07 UTC, merged