Tests for models
CESNET/perun-proxy-api pull request #64
Opened 2020-10-07 11:14 UTC by oernst9

Added tests for creating models
## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code or performance improvement
- [ ] Documentation changes or improvements

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My code has tests
- [ ] My code has been tested manually
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-08 08:56 UTC, dBucik requested changes
Minor changes, otherwise GTG :) Good Job! :+1:

2020-10-08 08:56 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntry.java
> +        if (externalNames.isEmpty()) {
Even better would be to use `!StringUtils.hasText(externalNames)` as it also checks if the trimmed string is empty.

2020-10-08 08:56 UTC, dBucik commented on src/test/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMappingTests.java
> +                AttributeType.STRING, "separator") );
It might be useful to consider passing a string containing whitespaces as well. However, I think it is OK as it is :) Take this just as advice for writing next tests.

2020-10-08 08:56 UTC, dBucik commented on src/test/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeTests.java
> +                "friendlyNameParameter", new ObjectMapper().createObjectNode()));
As well as using `new ObjectMapper().createObjectNode()` you can use `JsonNodeFactory.instance.objectNode()`. Just a hint, no need to change anything :)

2020-10-08 08:56 UTC, dBucik commented on src/test/java/cz/muni/ics/perunproxyapi/persistence/models/ResourceTests.java
> +}
Please add a missing newline at the end of the file.

2020-10-08 08:56 UTC, dBucik commented on src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntryTests.java
> +    @Test
Please insert a blank line between the class body start and Test annotation

2020-10-08 08:56 UTC, dBucik commented on src/test/java/cz/muni/ics/perunproxyapi/persistence/models/FacilityTests.java
> +    }
Please insert a blank line after this method

2020-10-08 08:56 UTC, dBucik commented on src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UserTests.java
> +        assertThrows(NullPointerException.class, () -> new User(1L, null,"s", new HashMap<>()));
Missing whitespace after the comma separating parameters.

This is actually happening in more methods, so please check all the changed files if it is OK in them as well.

2020-10-09 09:39 UTC, oernst9 commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntry.java
> +        if (externalNames.isEmpty()) {
externalNames is a list of strings

2020-10-09 10:38 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntry.java
> +        if (externalNames.isEmpty()) {
Ah sorry, my bad. Then it is OK :).

2020-10-09 10:39 UTC, dBucik approved these changes

2020-10-09 10:39 UTC, merged