ga4gh
CESNET/perun-proxy-api pull request #66
Opened 2020-10-08 14:43 UTC by BaranekD

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code or performance improvement
- [ ] Documentation changes or improvements

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My code has tests
- [x] My code has been tested manually
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2020-10-09 06:57 UTC, dBucik requested changes

2020-10-09 06:57 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PassportVisa.java
> +    }
I think we can use lomboks annotation and specify the JWT field to be excluded

2020-10-09 06:57 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +    public JsonNode ga4gh(@RequestParam(value = USER_ID) Long userId) throws NoSuchAlgorithmException, MalformedURLException, PerunConnectionException, FileNotFoundException, URISyntaxException, Peru
You are missing validation for the USER_ID param.

2020-10-09 06:57 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/interceptors/AddHeaderInterceptor.java
> +        this.header = header;
Header should not be empty string :)

2020-10-09 06:57 UTC, dBucik commented on src/main/resources/application.yml
> +  path: /etc/perun/keystore.jwks
I would rename this field to "config_file_path" or something similar that expresses more what value should the field contain. Even better would be something like "jwk_keystore_file_path"

2020-10-09 06:57 UTC, dBucik commented on src/test/resources/application.yml
> +  path: /etc/perun/keystore.jwks
Reflect changes made in the other application.yml file here as well.

2020-10-19 08:43 UTC, vyskocilpavel commented
@BaranekD Please rebase this PR. Thanks

2020-10-19 09:14 UTC, merged