Access decision api method
CESNET/perun-proxy-api pull request #71
Opened 2020-10-26 13:30 UTC by pavolpluta

## Description

Access Decision API method.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code or performance improvement
- [X] Documentation changes or improvements

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My code has tests
- [ ] My code has been tested manually
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2020-10-26 17:08 UTC, vyskocilpavel requested changes

2020-10-26 17:08 UTC, vyskocilpavel commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +    }
I think that these methods should be implemented directly in the adapter class.

2020-10-26 17:08 UTC, vyskocilpavel commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +    }
I think that these methods should be implemented directly in the adapter class.

2020-10-26 17:08 UTC, vyskocilpavel commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +        Set<Long> memberGroupIds = AdapterUtils.getLdapGroupIdsWhereUserIsMember(this, userId, MEMBER_OF);
Method getLdapGroupIdsWhereUserIsMember can me replace by method 'getGroupIdsWhereUserIsMember'. (This method can be implementet for both interface. Or better 'getGroupIdsWhereUserIsValidMember'

2020-10-26 17:08 UTC, vyskocilpavel commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +        Set<Long> memberVoIds = AdapterUtils.getLdapVoIdsWhereUserIsMember(this, userId, MEMBER_OF);
Method getLdapVoIdsWhereUserIsMember can me replace by method 'getVoIdsWhereUserIsMember'. (This method can be implementet for both interface. Or better 'getVoIdsWhereUserIsValidMember'

2020-10-27 06:46 UTC, dBucik requested changes

2020-10-27 06:46 UTC, dBucik commented on config_templates/relying-party-facade.yml.tpl
> +- methodName: "get_entitlements"
Why do you need to change this template at all?

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
> +        String isTestSpIdentifier = FacadeUtils.getStringOption(IS_TEST_SP, options);
I would say these options are required. You are usin methods for fetching optional configuration properties.

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
> +
I disagree. It is a utility method for fetching options in Long format. Keep it there, just get rid of the TODO comment.

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/RelyingPartyService.java
>  }
Add missing blank line

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/RelyingPartyFacade.java
>  }
Add missing blank line

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/RelyingPartyServiceImpl.java
> +        return adapter.isTestSp(facilityId, isTestSpIdentifier);
Do you really need to create a separate method in the adapter? I think it is enough to fetch the attribute and extract the value.

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/RelyingPartyServiceImpl.java
> +                                      @NonNull Long userId, @NonNull List<Long> voIds, String checkGroupMembershipAttrIdentifier, String isTestSpIdentifier)
What if the attribute identifiers are null? Also, I don't see any use of the _isTestSpidentifier_

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/AdapterUtils.java
> +        }
I don't agree with this behaviour. It is a configuration error, not a valid state. Remove the whole _if_ statement. Also the identifier must not be null.

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/AdapterUtils.java
> +        }
The same as above.

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/AdapterUtils.java
> +    public static boolean isTestSp(DataAdapter dataAdapter, Long facilityId, String isTestSpIdentifier)
Missing _@NonNull_ annotations on the parameters.

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/AdapterUtils.java
> +    }
If these are specific to the LDAP implementation, keep them in the LDAP adapter rather than extracting them into the Utils class. 

Utils class should contain methods that are common for at least more than two adapters (in this case both RPC and LDAP).

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
> +            throws PerunUnknownException, PerunConnectionException ;
Are these methods really needed? Wouldn't be just enough to call _getAttributeValue_ ?

2020-10-27 06:46 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
>      }
Why do you rewrite this method and then reintroduce it later in the code? Please just add the new method and do not change the old one.

2020-10-27 09:11 UTC, pavolpluta commented on config_templates/relying-party-facade.yml.tpl
> +- methodName: "get_entitlements"
Method find_by_identifiers should be in the proxyuser-facade, not here. I wanted to update this file to correspond with the real .yml file (just with the test data).

2020-10-27 10:07 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/RelyingPartyServiceImpl.java
> +        return adapter.isTestSp(facilityId, isTestSpIdentifier);
We don't. I've fetched attribute here. Done the same with the checkGroupMembership functionality.

2020-10-27 10:21 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
> +            throws PerunUnknownException, PerunConnectionException ;
Yes.

2020-10-27 10:52 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
>      }
I did not rewrite it. I made it public in the one commit, moved it to another place, meanwhile creating getAllowedGroups() at the place where getMembersByUser() was before. In the last commit, I decided to make first method private again and moved in to the original place. Second method is under the first one now, you can find both of them in the class. You are probably seeing changes just from the last commit. This is some strange behaviour from github, as both methods are probably pretty similar and github don't show changes I was doing with the first method during the pull request. In the end, first method is the same as before the pull request, just on the different lines.

2020-10-27 11:02 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +        Set<Long> memberGroupIds = AdapterUtils.getLdapGroupIdsWhereUserIsMember(this, userId, MEMBER_OF);
There is method in RPC called getUserGroups(), which provides this functionality (it just returns groups, not group ids). Should I rename that rpc method, to make it more consistent? @dBucik, what do you think about this?

2020-10-29 06:27 UTC, dBucik commented on config_templates/relying-party-facade.yml.tpl
> +- methodName: "get_entitlements"
You are right, thank you for noticing that!

2020-10-29 06:28 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +        Set<Long> memberGroupIds = AdapterUtils.getLdapGroupIdsWhereUserIsMember(this, userId, MEMBER_OF);
I would prefer introducing a new method. If the mentioned one would not be used, we can remove it in the future.

2020-10-29 06:29 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
>      }
Okay, no problem. If it is just a weird way how GH displays it, then I am fine with it.

2020-11-02 15:12 UTC, dBucik requested changes
Just some minor improvements, one thing that I would appreciate if @vyskocilpavel  could add his opinion.

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
> +        List<Long> voIds = isTestSp ? FacadeUtils.getRequiredLongListOption(TEST_VO_IDS, HAS_ACCESS_TO_SERVICE, options) :
Well, I would prefer fetching all the options in the facade and passing them to the service. So the service layer would actually decide based on the value obtained from adapter which of the passed lists should be used.
@vyskocilpavel What do you think? Should we move fetching of the "isTestSp" to the service layer?

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
> +    Set<Long> getGroupIdsWhereUserIsValidMember(Long userId) throws PerunUnknownException, PerunConnectionException;
Missing `@NonNull` annotation on the parameters.

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +                voIds.add(Long.parseLong(voId));
Missing whitespaces separating passed parameters at some places.

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +                groupId = groupId.replace(PERUN_GROUP_ID + '=',"");
Missing whitespaces separating passed parameters at some places.

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +    public List<Group> getFacilityGroupsWhereUserIsValidMember(Long userId, Long facilityId) throws PerunUnknownException, PerunConnectionException {
Missing `@NonNull` annotation on the parameters.

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +    public boolean isValidMemberOfAnyProvidedVo(Long userId, List<Long> voIds) throws PerunUnknownException, PerunConnectionException {
Missing `@NonNull` annotation on the parameters.

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +        return isValidMemberOfVo;
You can use `return !Collections.disjoint(voIds, memberVoIds);`

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +        return voIds;
No need to store it in a variable, inline the return statement

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +        return groupIds;
No need to store it in a variable, inline the return statement

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +    public Set<Long> getVoIdsWhereUserIsValidMember(Long userId) throws PerunUnknownException, PerunConnectionException {
Missing @NonNull annotation on the parameters.

2020-11-02 15:12 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +    public Set<Long> getGroupIdsWhereUserIsValidMember(Long userId) throws PerunUnknownException, PerunConnectionException {
Missing @NonNull annotation on the parameters.

2020-11-03 13:22 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +                voIds.add(Long.parseLong(voId));
This one is not visible in my IDE as IDEA shows parameter hints, making invisible whether the spaces between parameters exist or not. Thanks for noticing this.

2020-11-03 13:26 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
> +                groupId = groupId.replace(PERUN_GROUP_ID + '=',"");
This one is problematic in IDE, as IDEA shows parameter hints, making it very badly visible, whether spaces between parameters exist or not. Thanks for noticing this.

2020-11-03 13:30 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
> +        return voIds;
I've done it just for the sake of readability, but I understand it is probably redundant.

2020-11-03 14:03 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
> +        List<Long> voIds = isTestSp ? FacadeUtils.getRequiredLongListOption(TEST_VO_IDS, HAS_ACCESS_TO_SERVICE, options) :
I'll wait for Pavel's response.

2020-11-04 08:54 UTC, vyskocilpavel commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
> +        List<Long> voIds = isTestSp ? FacadeUtils.getRequiredLongListOption(TEST_VO_IDS, HAS_ACCESS_TO_SERVICE, options) :
I agree with @dBucik .

2020-11-04 13:00 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
> +        List<Long> voIds = isTestSp ? FacadeUtils.getRequiredLongListOption(TEST_VO_IDS, HAS_ACCESS_TO_SERVICE, options) :
I made the requested changes. However, there are many parameters being passed between facade and service layer. I suggest creating some class which will serve as the storage for all these options. We can use it in cases like this one, where we have to use many parameters from the config file (in this method, we are getting and passing 4 parameters). Then we can use this class (or its instance if it won't be static) as a parameter for the method from service layer, instead of the options. I can create another pull request with such a class above this one. What do you think? @vyskocilpavel @dBucik

2020-11-05 11:31 UTC, merged