createMemberInVO API method - IN PROGRESS
CESNET/perun-proxy-api pull request #74
Opened 2020-11-26 13:48 UTC by pavolpluta

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code or performance improvement
- [ ] Documentation changes or improvements

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My code has tests
- [ ] My code has been tested manually
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-12-14 06:50 UTC, dBucik requested changes
Just small changes needed, otherwise, it seems quite OK. Have you been also testing it manually?

2020-12-14 06:50 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
> +            if (requestAttributes.get(loginAttr).textValue() != null) {
Check for a nonempty string might be a good idea as well.

2020-12-14 06:50 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/RelyingPartyService.java
> +    boolean createMemberInVo(@NonNull FullAdapter rpcAdapter, @NonNull String extSourceIdentifier, @NonNull Long voId,
This method is about the user, not about the relying party. Please move it to the correct class.

2020-12-14 06:50 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/ServiceUtils.java
> +        attributes.forEach((attrName, attrValue) -> {
Some normalization of the attr names might be a good idea. I.e., we could use only LOWERCASE names.

2020-12-14 06:50 UTC, dBucik commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/ServiceUtils.java
> +                    throw new ConfigurationException(String.format("Configuration file does not provide mapping for attribute '%s'", attrName));
I think it is enough to log this fact and continue with the execution instead.

2020-12-15 15:28 UTC, pavolpluta commented on src/main/java/cz/muni/ics/perunproxyapi/application/service/ServiceUtils.java
> +        attributes.forEach((attrName, attrValue) -> {
Attr names from request equals to attr values in configuration -> candidate_attr_mapper. Do we really want to make changes programmatically? Wouldn't it be sufficient to just set attr values in the configuration properly?

2020-12-16 07:46 UTC, vyskocilpavel commented on src/test/resources/configs/proxyuser-facade.yml
> +      firstName: "cn"
cn is commonName.

Should be givenName on this line

2020-12-16 11:18 UTC, vyskocilpavel commented on src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> +     *   --url http://localhost:8081/papi/auth/relying-party/createMemberInVo \
bad example URL

2021-01-08 06:37 UTC, merged